stages:
  - restart

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_DRIVER: overlay2

image: docker:20.10.16

services:
  - docker:20.10.16-dind

before_script:
  - for try in {1..10}; do sleep 0.5; docker info && break ; done
  - echo "$YC_REGISTRY_KEY" | docker login -u "$YC_REGISTRY_USER" --password-stdin $CI_REGISTRY

restart_vm:
  stage: restart
  when: manual
  script:
    - docker run --rm -e YC_INSTANCE_ID="$YC_INSTANCE_ID" -e YC_SA_KEY="$YC_SA_KEY" -e YC_SA_ID="$YC_SA_ID" -e YC_SA_PARENT_ID="$YC_SA_PARENT_ID" "$CI_REGISTRY/cloud-tools/init:v2.1"
