include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"

.global-variables:
  variables:
    SSH_USER: "$NAME_VM"
    SSH_HOST: "$HOST"
    SSH_PRIVATE_KEY_BASE64: "$SSH_KEY"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
  variables:
    OPT_DOCKER: "-p 80:80"
