include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
  variables:
    OPT_DOCKER: "-p 8080:8080"
  before_script:
    # SSH setup
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - "echo -e 'Host *\n\tStrictHostKeyChecking no\n' > ~/.ssh/config"
    - chmod 600 ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa

    # Debugging
    - echo Checking SSH_HOST:"$SSH_HOST"
    - set -x
    - ssh-keyscan -H -p 22 "$SSH_HOST" > ~/.ssh/known_hosts
    - set +x
    - chmod 644 ~/.ssh/known_hosts

    # Connection check
    - nc -zvw3 "$SSH_HOST" 22 || true