stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "avatar-generator"
  PROJECT_DIR: "/opt/avatar-service"
  DOCKER_HOST: "tcp://docker:2375"

default:
  image: docker:24.0
  services:
    - docker:24.0-dind

build:
  stage: build
  extends: default
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  extends: .default
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$ENV_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $ENV_SSH_HOST > ~/.ssh/known_hosts
  script:
    - |
      ssh $ENV_SSH_USER@$ENV_SSH_HOST <<EOF
      mkdir -p $PROJECT_DIR
      docker pull $CI_REGISTRY_IMAGE
      docker stop avatar-service || true
      docker rm avatar-service || true
      docker run -d \
        --name avatar-service \
        -p 80:80 \
        -v $PROJECT_DIR/data:/app/PROJECT/data \
        $CI_REGISTRY_IMAGE
      EOF
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH